# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 009414b2159e99b226c9a40b6193241c84c7b09f4627a38001fff881423566ff4af91780dcc0db411faa2b171b25c38f482ffeda86f3548e6ea64c834faa34ac

test:
  secret_key_base: b10b0277e31274d955f1f8189b4734f26743e9361fb14689bd73a0d922c319a881f91efd1edfac8f55cc14a33a6929d466987bccc081b8ae8790ba580ebdd23f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
